// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPa1W4i1V718TVmWEp49PRfWhICSUuYPk',
    appId: '1:249165555109:web:3afd772b5c774f7773744c',
    messagingSenderId: '249165555109',
    projectId: 'auth-test-972e0',
    authDomain: 'auth-test-972e0.firebaseapp.com',
    storageBucket: 'auth-test-972e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Bc3R25VFUrEDFn8r5eVjYvMYpzTNKPY',
    appId: '1:249165555109:android:c6f2b40c5516863f73744c',
    messagingSenderId: '249165555109',
    projectId: 'auth-test-972e0',
    storageBucket: 'auth-test-972e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNGgpvJWMVoKkKJExYbNEKYvaSjNNJgE',
    appId: '1:249165555109:ios:fc88e36731a16bf873744c',
    messagingSenderId: '249165555109',
    projectId: 'auth-test-972e0',
    storageBucket: 'auth-test-972e0.appspot.com',
    iosClientId: '249165555109-035pou9u7538c886ligqc2kp181sksjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
